<template>
  <section class="profileImg">
    <img
      src="https://img.freepik.com/free-vector/cute-astronaut-peace-moon-with-rocket-cartoon-vector-icon-illustration-science-technology-icon_138676-5030.jpg"
    />
    <img
      src="https://resources.premierleague.com/premierleague/photos/players/250x250/p235674.png"
    />
    <img
      src="https://img.freepik.com/free-vector/cute-astronaut-peace-moon-with-rocket-cartoon-vector-icon-illustration-science-technology-icon_138676-5030.jpg"
    />
    <img
      src="https://resources.premierleague.com/premierleague/photos/players/250x250/p235674.png"
    />
    <img
      src="https://img.freepik.com/free-vector/cute-astronaut-peace-moon-with-rocket-cartoon-vector-icon-illustration-science-technology-icon_138676-5030.jpg"
    />
    <img
      src="https://img.freepik.com/free-vector/cute-astronaut-peace-moon-with-rocket-cartoon-vector-icon-illustration-science-technology-icon_138676-5030.jpg"
    />
    <img
      src="https://img.freepik.com/free-vector/cute-astronaut-peace-moon-with-rocket-cartoon-vector-icon-illustration-science-technology-icon_138676-5030.jpg"
    />
    <img
      class="profileImg"
      src="https://img.freepik.com/free-vector/cute-astronaut-peace-moon-with-rocket-cartoon-vector-icon-illustration-science-technology-icon_138676-5030.jpg"
    />
  </section>
</template>
<script>
export default {};
</script>
